#pragma once

#define HEIGHT 140
#define WIDTH 480

#define NUMBER_HEIGHT 7
#define NUMBER_WIDTH 10


#define MARIO_HEIGHT 16
#define MARIO_WIDTH 32

#define GUMBA_HEIGHT 16
#define GUMBA_WIDTH 32

#define TURTLE_HEIGHT 32
#define TURTLE_WIDTH 32

#define KOOPA_HEIGHT 32
#define KOOPA_WIDTH 64

#define SMALL_CLOUD_HEIGHT 32
#define SMALL_CLOUD_WIDTH 64

#define SMALL_BUSH_HEIGHT 16
#define SMALL_BUSH_WIDTH 64

#define PIPE_BODY_HEIGHT 16
#define PIPE_BODY_WIDTH 64

#define PIPE_TOP_HEIGHT 16
#define PIPE_TOP_WIDTH 64

#define BRICK_HEIGHT 16
#define BRICK_WIDTH 32

#define THORN_HEIGHT 16
#define THORN_WIDTH 32

#define PODOBOO_HEIGHT 16
#define PODOBOO_WIDTH 32

#define YES 1
#define NO 0

#define LEFT 1
#define RIGHT 2
#define UP 3

#define VK_C 0x43
#define VK_LEFT 75
#define VK_RIGHT 77


#define DIRT_LEFT 0
#define DIRT_RIGHT 1

enum Arrow { L, R, U };

enum BackGroundObj { SMALL_CLOUD, SMALL_BUSH, PIPE_TOP, PIPE_BODY, KOOPA, DOOR,DOORWHITE, DOORWHITEREVERSE, BRICK,BRICK_GRAY,THORN, HAMMER, DOORBOSS};